overwritten sending to cspm panel

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -103,6 +103,25 @@ runs:
         # Replace original with updated file
         mv "$TEMP_JSON_FILE" "$JSON_FILE"
 
+    - name: Push report to CSPM panel
+      shell: bash
+      run: |
+        if [[ ! -s results.json ]]; then
+          echo "No Issues found. Skipping API upload."
+          exit 0
+        fi
+        
+        RESPONSE=$(curl --location "https://${{ inputs.endpoint }}/api/v1/artifact/?tenant_id=${{ inputs.tenant_id }}&data_type=SG&save_to_s3=true&label_id=${{ inputs.label }}" \
+            --header "Tenant-Id: ${{ inputs.tenant_id }}" \
+            --header "Authorization: Bearer ${{ inputs.token }}" \
+            --form "file=@./results.json")
+
+        echo "Response: $RESPONSE"
+        if [[ "$RESPONSE" != *"File received successfully"* ]]; then
+          echo "Error: Failed to push report to CSPM panel"
+          exit 1
+        fi
+
 outputs:
   results-file:
     description: 'Path to the JSON results file'
